# Generated by Django 2.2.1 on 2019-05-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_song_hotcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='hotComment',
            new_name='closedCommentCount',
        ),
        migrations.AddField(
            model_name='song',
            name='hotCommentCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='insertDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='updateDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
