# Generated by Django 2.2.1 on 2019-05-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_auto_20190508_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('province', models.IntegerField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('nickName', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('likedCount', models.IntegerField(blank=True, null=True)),
                ('commentTime', models.DateTimeField(blank=True, null=True)),
                ('insertDate', models.DateTimeField(blank=True, null=True)),
                ('updateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
