# Generated by Django 2.2.1 on 2019-05-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0004_auto_20190508_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('province', models.IntegerField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('nickName', models.TextField(blank=True, null=True)),
                ('eventTime', models.DateTimeField(blank=True, null=True)),
                ('insertDate', models.DateTimeField(blank=True, null=True)),
                ('updateDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.IntegerField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('nickName', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
