# Generated by Django 2.2.1 on 2019-05-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0005_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='threadId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
