# Generated by Django 2.2.1 on 2019-05-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0007_auto_20190521_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='threadId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
