# Generated by Django 2.2.1 on 2019-06-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0008_auto_20190528_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
