# Generated by Django 2.2.1 on 2019-06-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0009_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
