# Generated by Django 2.2.1 on 2019-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0011_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='canceld',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
