# Generated by Django 2.2.1 on 2019-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0012_comment_canceld'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='musicId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
