# Generated by Django 2.2.3 on 2019-09-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0014_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='emotion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
