# Generated by Django 2.2.3 on 2019-09-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0015_sentence_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
